### ISSUE TITLE
[Question] Does Airtable Proxy cache by default?

### ISSUE THREAD

**Issue by curtishall** [portable-cto/airtable-proxy-worker#3]
I successfully deployed the worker to Cloudflare.  Do I need to change anything in the worker script to enable caching?  I noticed the cache time was set to 0, should I change that to something higher?

Great product btw, good work.

Thanks

**Comment by karllhughes** [comment]
@curtishall the cache time defaults to `0` which effectively disables caching. So, if you want to cache results, just specify the number of seconds in the `PROXY_CACHE_TIME` environment variable.

For example, `PROXY_CACHE_TIME=2` will cache results from each Airtable call for 2 seconds.

Hope that helps and glad the library is helpful!
